language: python
python:
  - 2.6
  - 2.7
  - 3.2
  - 3.3
env:
    - DJANGO='django>=1.4,<1.5'
    - DJANGO='django>=1.5'
matrix:
    exclude:
        -   python: 3.2
            env: DJANGO='django>=1.4,<1.5'
        -   python: 3.3
            env: DJANGO='django>=1.4,<1.5'
install:
  - pip install $DJANGO pep8 --use-mirrors
# command to run tests
script: make test pep8
